<?php
/**
 * @see Mage_Catalog_Block_Product_View_Type_Grouped
 */
$this->setPreconfiguredValue();
$_product = $this->getProduct();
$_associatedProducts = $this->getAssociatedProducts();
$_hasAssociatedProducts = count($_associatedProducts) > 0;
?>
<div openwire="catalog/product_view_type_grouped" data-ui="vue:Catalog/Product/View/Type/Grouped"
    data-props='<?= json_encode([
        'isSaleable' => (bool) $_product->isSaleable(),
        'associatedProducts' => array_map(function($_item) use ($_product, $this) {
            return [
                'id' => $_item->getId(),
                'name' => $_item->getName(),
                'is_saleable' => $_item->isSaleable(),
                'qty' => $_item->getQty() * 1,
                'price_html' => $this->getPriceHtml($_item, true),
                'tier_price_html' => $this->getTierPriceHtml($_item),
                'thumbnail' => (string)$this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(true)->resize(105, 80),
                'thumbnail2x' => (string)$this->helper('catalog/image')->init($_item, 'thumbnail')->constrainOnly(true)->resize(210, 160),
                'image_label' => $this->escapeHtml($this->getImageLabel())
            ];
        }, $_associatedProducts),
        'hasAssociatedProducts' => $_hasAssociatedProducts,
        'canShowProductPrice' => $this->getCanShowProductPrice($_product)
    ]) ?>'>
    <slot name="product_type_data_extra"><?= $this->getChildHtml('product_type_data_extra') ?></slot>
</div>
