<?php
/**
 * @see Mage_Catalog_Block_Product_View_Options_Type_File
 */
$option = $this->getOption();
$optionId = $option->getId();
$fileInfo = $this->getFileInfo();
$fileExists = (bool) $fileInfo->hasData();
$fileName = "options_{$option->getId()}_file";
$fieldNameAction = "{$fileName}_action";
$fieldValueAction = $fileExists ? 'save_old' : 'save_new';
$fileNamed = "{$fileName}_name";
?>
<div openwire="catalog/product_view_options_type_file" data-ui="vue:Catalog/Product/View/Options/Type/File"
    data-props='<?= json_encode([
        'option' => [
            'id' => $optionId,
            'title' => $option->getTitle(),
            'isRequired' => $option->getIsRequired(),
            'imageSizeX' => $option->getImageSizeX(),
            'imageSizeY' => $option->getImageSizeY()
        ],
        'formatedPrice' => $this->getFormatedPrice(),
        'fileInfo' => $fileExists ? [
            'title' => $fileInfo->getTitle()
        ] : null,
        'fileName' => $fileName,
        'fieldNameAction' => $fieldNameAction,
        'fieldValueAction' => $fieldValueAction,
        'fileNamed' => $fileNamed,
        'sanitizedExtensions' => $this->getSanitizedFileExtension(),
        'maxFileSizeMb' => $this->getMaxFileSizeMb()
    ]) ?>'>
</div>
