#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "maho" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'maho' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER maho
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    if [ ! -d /var/www/html/public ]; then
        echo "Waiting for /var/www/html/public to be available..."
        for i in $(seq 1 30); do
            [ -d /var/www/html/public ] && break
            sleep 1
        done
        if [ ! -d /var/www/html/public ]; then
            echo "Timeout: /var/www/html/public still missing." >&2
            exit 1
        fi
        echo "Directory ready."
    fi
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
